config {
    type: "assertion",
    database: "sample-training-001",
    schema: constants.TARGET_SCHEMA,
    name: "assert_gold_check",
    description: "Fails if the weather_gold_table has 0 rows before running transformations."
}

  -- Assertions FAIL if the query returns any rows.
  -- This query returns 1 row ONLY if the bronze table is completely empty.
WITH check_empty AS (
  SELECT 
    CASE WHEN COUNT(*) = 0 THEN 'TABLE_IS_EMPTY' END AS status
  FROM 
    ${ref("weather_gold_table")}
)

SELECT 
  * 
FROM 
  check_empty 
WHERE 
  status IS NOT NULL
